name: Déploiement FTP vers O2switch

on:
  push:
    branches:
      - master  # ou main, selon ton dépôt

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Déploiement via FTP
        uses: SamKirkland/FTP-Deploy-Action@v3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
